### ISSUE TITLE
Highlight disabled Button

### ISSUE THREAD

**Issue by tboehm-xdev** [vaadin/vaadin-button-flow#139] opened 2019-06-25 07:10 UTC
On Button.setEnabled(false) only the mouse-over effect disappears.

The button should be highlighted or better gain some grey backgroundcolor.

Combobox.setEnabled(false) works fine - they get an grey color

**Comment by web-padawan** [comment] 2020-02-13 14:55
This is working now: https://vaadin.com/components/vaadin-button/java-examples

See "Disabled button" and "Button disabled on click" demos.

![disabled](https://user-images.githubusercontent.com/10589913/74447087-75a95200-4e81-11ea-9ace-72dec2b8fe90.png)

Not sure if something was broken, as the issue is quite outdated. So I'm closing as invalid.

**Closed by web-padawan** 2020-02-13 14:55 UTC
Labels: invalid
