### ISSUE TITLE
disableOnClick not working when button is detached and attached again

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-button-flow#169] opened 2020-08-31 08:44 UTC
Based on https://stackoverflow.com/questions/63634513/reliability-of-button-disableonclick-in-vaadin-14

Basically the initialization code `initDisableOnClick` should be executed always when the button is attached. Currently it is easily broken when either `@PreserveOnRefresh` is used or when the button is inside a dialog that is closed and reopened.

**Comment by tomivirkki** [comment] 2020-09-08 11:21
Closing as a duplicate of https://github.com/vaadin/vaadin-button-flow/issues/171

**Closed by tomivirkki** 2020-09-08 11:21 UTC
Labels: Impact: Low, Severity: Minor, bug
